[package]
name = "rsrelex"
version = "0.1.0"
authors = ["mwelt <michael.welt@non-of-your-bussiness.de>"]
edition = "2020"

[dependencies]
unicode-segmentation = "1.6.0"
quick-xml = "0.17.2"
bincode = "1.2.1"
serde = { version = "1.0.104", features = ["derive"] }